//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBS.IT.Utilities.DataAccess.TimeTrackerDb.Edmx
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class TimeTrackerEntities : DbContext
    {
        public TimeTrackerEntities()
            : base("name=TimeTrackerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<usp_WorkType_Get_Result> usp_WorkType_Get(Nullable<int> isActive)
        {
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("isActive", isActive) :
                new ObjectParameter("isActive", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_WorkType_Get_Result>("usp_WorkType_Get", isActiveParameter);
        }
    
        public virtual int usp_Team_Add(string teamCode, string teamName, string description, Nullable<int> createUserId, ObjectParameter teamId)
        {
            var teamCodeParameter = teamCode != null ?
                new ObjectParameter("teamCode", teamCode) :
                new ObjectParameter("teamCode", typeof(string));
    
            var teamNameParameter = teamName != null ?
                new ObjectParameter("teamName", teamName) :
                new ObjectParameter("teamName", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("description", description) :
                new ObjectParameter("description", typeof(string));
    
            var createUserIdParameter = createUserId.HasValue ?
                new ObjectParameter("createUserId", createUserId) :
                new ObjectParameter("createUserId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_Team_Add", teamCodeParameter, teamNameParameter, descriptionParameter, createUserIdParameter, teamId);
        }
    
        public virtual ObjectResult<usp_Team_Get_Result> usp_Team_Get(Nullable<int> isActive)
        {
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("isActive", isActive) :
                new ObjectParameter("isActive", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_Team_Get_Result>("usp_Team_Get", isActiveParameter);
        }
    
        public virtual ObjectResult<usp_TimeZone_Get_Result> usp_TimeZone_Get(Nullable<int> isActive)
        {
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("isActive", isActive) :
                new ObjectParameter("isActive", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_TimeZone_Get_Result>("usp_TimeZone_Get", isActiveParameter);
        }
    
        public virtual int usp_WorkType_Delete(Nullable<int> deleteUserId, Nullable<int> workTypeId)
        {
            var deleteUserIdParameter = deleteUserId.HasValue ?
                new ObjectParameter("deleteUserId", deleteUserId) :
                new ObjectParameter("deleteUserId", typeof(int));
    
            var workTypeIdParameter = workTypeId.HasValue ?
                new ObjectParameter("workTypeId", workTypeId) :
                new ObjectParameter("workTypeId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_WorkType_Delete", deleteUserIdParameter, workTypeIdParameter);
        }
    
        public virtual int usp_Application_Add(string applicationCode, string applicationName, string description, Nullable<int> createUserId, ObjectParameter applicationId)
        {
            var applicationCodeParameter = applicationCode != null ?
                new ObjectParameter("applicationCode", applicationCode) :
                new ObjectParameter("applicationCode", typeof(string));
    
            var applicationNameParameter = applicationName != null ?
                new ObjectParameter("applicationName", applicationName) :
                new ObjectParameter("applicationName", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("description", description) :
                new ObjectParameter("description", typeof(string));
    
            var createUserIdParameter = createUserId.HasValue ?
                new ObjectParameter("createUserId", createUserId) :
                new ObjectParameter("createUserId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_Application_Add", applicationCodeParameter, applicationNameParameter, descriptionParameter, createUserIdParameter, applicationId);
        }
    
        public virtual ObjectResult<usp_Application_Get_Result> usp_Application_Get(Nullable<int> isActive)
        {
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("isActive", isActive) :
                new ObjectParameter("isActive", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_Application_Get_Result>("usp_Application_Get", isActiveParameter);
        }
    
        public virtual int usp_ProjectItem_Delete(Nullable<int> projectItemId, Nullable<int> deleteUserId)
        {
            var projectItemIdParameter = projectItemId.HasValue ?
                new ObjectParameter("projectItemId", projectItemId) :
                new ObjectParameter("projectItemId", typeof(int));
    
            var deleteUserIdParameter = deleteUserId.HasValue ?
                new ObjectParameter("deleteUserId", deleteUserId) :
                new ObjectParameter("deleteUserId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_ProjectItem_Delete", projectItemIdParameter, deleteUserIdParameter);
        }
    
        public virtual int usp_Project_Delete(Nullable<int> projectId, Nullable<int> deleteUserId)
        {
            var projectIdParameter = projectId.HasValue ?
                new ObjectParameter("projectId", projectId) :
                new ObjectParameter("projectId", typeof(int));
    
            var deleteUserIdParameter = deleteUserId.HasValue ?
                new ObjectParameter("deleteUserId", deleteUserId) :
                new ObjectParameter("deleteUserId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_Project_Delete", projectIdParameter, deleteUserIdParameter);
        }
    
        public virtual int usp_Employee_Delete(Nullable<int> employeeId, Nullable<int> deleteUserId)
        {
            var employeeIdParameter = employeeId.HasValue ?
                new ObjectParameter("employeeId", employeeId) :
                new ObjectParameter("employeeId", typeof(int));
    
            var deleteUserIdParameter = deleteUserId.HasValue ?
                new ObjectParameter("deleteUserId", deleteUserId) :
                new ObjectParameter("deleteUserId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_Employee_Delete", employeeIdParameter, deleteUserIdParameter);
        }
    
        public virtual int usp_Application_Delete(Nullable<int> applicationId, Nullable<int> deleteUserId)
        {
            var applicationIdParameter = applicationId.HasValue ?
                new ObjectParameter("applicationId", applicationId) :
                new ObjectParameter("applicationId", typeof(int));
    
            var deleteUserIdParameter = deleteUserId.HasValue ?
                new ObjectParameter("deleteUserId", deleteUserId) :
                new ObjectParameter("deleteUserId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_Application_Delete", applicationIdParameter, deleteUserIdParameter);
        }
    
        public virtual int usp_Application_Update(Nullable<int> applicationId, string applicationCode, string applicationName, string description, Nullable<int> isActive, Nullable<int> updateUserId)
        {
            var applicationIdParameter = applicationId.HasValue ?
                new ObjectParameter("applicationId", applicationId) :
                new ObjectParameter("applicationId", typeof(int));
    
            var applicationCodeParameter = applicationCode != null ?
                new ObjectParameter("applicationCode", applicationCode) :
                new ObjectParameter("applicationCode", typeof(string));
    
            var applicationNameParameter = applicationName != null ?
                new ObjectParameter("applicationName", applicationName) :
                new ObjectParameter("applicationName", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("description", description) :
                new ObjectParameter("description", typeof(string));
    
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("isActive", isActive) :
                new ObjectParameter("isActive", typeof(int));
    
            var updateUserIdParameter = updateUserId.HasValue ?
                new ObjectParameter("updateUserId", updateUserId) :
                new ObjectParameter("updateUserId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_Application_Update", applicationIdParameter, applicationCodeParameter, applicationNameParameter, descriptionParameter, isActiveParameter, updateUserIdParameter);
        }
    
        public virtual ObjectResult<usp_Employee_GetManager_Result> usp_Employee_GetManager()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_Employee_GetManager_Result>("usp_Employee_GetManager");
        }
    
        public virtual ObjectResult<string> usp_TimeEntry_GetLastEntry(Nullable<int> employeeId, Nullable<System.DateTime> productionDate)
        {
            var employeeIdParameter = employeeId.HasValue ?
                new ObjectParameter("employeeId", employeeId) :
                new ObjectParameter("employeeId", typeof(int));
    
            var productionDateParameter = productionDate.HasValue ?
                new ObjectParameter("ProductionDate", productionDate) :
                new ObjectParameter("ProductionDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("usp_TimeEntry_GetLastEntry", employeeIdParameter, productionDateParameter);
        }
    
        public virtual ObjectResult<usp_Employee_GetList_Result> usp_Employee_GetList(Nullable<int> managerId)
        {
            var managerIdParameter = managerId.HasValue ?
                new ObjectParameter("managerId", managerId) :
                new ObjectParameter("managerId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_Employee_GetList_Result>("usp_Employee_GetList", managerIdParameter);
        }
    
        public virtual ObjectResult<usp_Application_Search_Result> usp_Application_Search(Nullable<int> applicationId, string searchBy, Nullable<int> pageSize, Nullable<int> pageNumber, Nullable<bool> sortOrder, string sortColumn)
        {
            var applicationIdParameter = applicationId.HasValue ?
                new ObjectParameter("applicationId", applicationId) :
                new ObjectParameter("applicationId", typeof(int));
    
            var searchByParameter = searchBy != null ?
                new ObjectParameter("searchBy", searchBy) :
                new ObjectParameter("searchBy", typeof(string));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("pageSize", pageSize) :
                new ObjectParameter("pageSize", typeof(int));
    
            var pageNumberParameter = pageNumber.HasValue ?
                new ObjectParameter("pageNumber", pageNumber) :
                new ObjectParameter("pageNumber", typeof(int));
    
            var sortOrderParameter = sortOrder.HasValue ?
                new ObjectParameter("sortOrder", sortOrder) :
                new ObjectParameter("sortOrder", typeof(bool));
    
            var sortColumnParameter = sortColumn != null ?
                new ObjectParameter("sortColumn", sortColumn) :
                new ObjectParameter("sortColumn", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_Application_Search_Result>("usp_Application_Search", applicationIdParameter, searchByParameter, pageSizeParameter, pageNumberParameter, sortOrderParameter, sortColumnParameter);
        }
    
        public virtual ObjectResult<usp_ProjectType_Get_Result> usp_ProjectType_Get(Nullable<int> isActive)
        {
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("isActive", isActive) :
                new ObjectParameter("isActive", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ProjectType_Get_Result>("usp_ProjectType_Get", isActiveParameter);
        }
    
        public virtual ObjectResult<usp_ProjectItemStatus_Get_Result> usp_ProjectItemStatus_Get(Nullable<int> isActive)
        {
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("isActive", isActive) :
                new ObjectParameter("isActive", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ProjectItemStatus_Get_Result>("usp_ProjectItemStatus_Get", isActiveParameter);
        }
    
        public virtual ObjectResult<usp_WorkType_Search_Result> usp_WorkType_Search(Nullable<int> workTypeId, string searchBy, Nullable<int> pageSize, Nullable<int> pageNumber, Nullable<bool> sortOrder, string sortColumn)
        {
            var workTypeIdParameter = workTypeId.HasValue ?
                new ObjectParameter("workTypeId", workTypeId) :
                new ObjectParameter("workTypeId", typeof(int));
    
            var searchByParameter = searchBy != null ?
                new ObjectParameter("searchBy", searchBy) :
                new ObjectParameter("searchBy", typeof(string));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("pageSize", pageSize) :
                new ObjectParameter("pageSize", typeof(int));
    
            var pageNumberParameter = pageNumber.HasValue ?
                new ObjectParameter("pageNumber", pageNumber) :
                new ObjectParameter("pageNumber", typeof(int));
    
            var sortOrderParameter = sortOrder.HasValue ?
                new ObjectParameter("sortOrder", sortOrder) :
                new ObjectParameter("sortOrder", typeof(bool));
    
            var sortColumnParameter = sortColumn != null ?
                new ObjectParameter("sortColumn", sortColumn) :
                new ObjectParameter("sortColumn", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_WorkType_Search_Result>("usp_WorkType_Search", workTypeIdParameter, searchByParameter, pageSizeParameter, pageNumberParameter, sortOrderParameter, sortColumnParameter);
        }
    
        public virtual ObjectResult<usp_EmploymentType_Get_Result> usp_EmploymentType_Get(Nullable<int> isActive)
        {
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("isActive", isActive) :
                new ObjectParameter("isActive", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_EmploymentType_Get_Result>("usp_EmploymentType_Get", isActiveParameter);
        }
    
        public virtual ObjectResult<usp_Location_Get_Result> usp_Location_Get(Nullable<int> isActive)
        {
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("isActive", isActive) :
                new ObjectParameter("isActive", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_Location_Get_Result>("usp_Location_Get", isActiveParameter);
        }
    
        public virtual ObjectResult<usp_UserType_Get_Result> usp_UserType_Get(Nullable<int> isActive)
        {
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("isActive", isActive) :
                new ObjectParameter("isActive", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_UserType_Get_Result>("usp_UserType_Get", isActiveParameter);
        }
    
        public virtual ObjectResult<usp_WorkTypeCategory_Get_Result> usp_WorkTypeCategory_Get(Nullable<int> isActive)
        {
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("isActive", isActive) :
                new ObjectParameter("isActive", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_WorkTypeCategory_Get_Result>("usp_WorkTypeCategory_Get", isActiveParameter);
        }
    
        public virtual int usp_WorkType_Add(string workTypeCode, string workTypeName, string description, Nullable<int> workTypeCategoryId, Nullable<int> isCapitalizable, Nullable<int> createUserId, ObjectParameter workTypeId)
        {
            var workTypeCodeParameter = workTypeCode != null ?
                new ObjectParameter("workTypeCode", workTypeCode) :
                new ObjectParameter("workTypeCode", typeof(string));
    
            var workTypeNameParameter = workTypeName != null ?
                new ObjectParameter("workTypeName", workTypeName) :
                new ObjectParameter("workTypeName", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("description", description) :
                new ObjectParameter("description", typeof(string));
    
            var workTypeCategoryIdParameter = workTypeCategoryId.HasValue ?
                new ObjectParameter("WorkTypeCategoryId", workTypeCategoryId) :
                new ObjectParameter("WorkTypeCategoryId", typeof(int));
    
            var isCapitalizableParameter = isCapitalizable.HasValue ?
                new ObjectParameter("isCapitalizable", isCapitalizable) :
                new ObjectParameter("isCapitalizable", typeof(int));
    
            var createUserIdParameter = createUserId.HasValue ?
                new ObjectParameter("createUserId", createUserId) :
                new ObjectParameter("createUserId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_WorkType_Add", workTypeCodeParameter, workTypeNameParameter, descriptionParameter, workTypeCategoryIdParameter, isCapitalizableParameter, createUserIdParameter, workTypeId);
        }
    
        public virtual int usp_WorkType_Update(string workTypeCode, string workTypeName, string description, Nullable<int> workTypeCategoryId, Nullable<int> isCapitalizable, Nullable<int> isActive, Nullable<int> updateUserId, Nullable<int> workTypeId)
        {
            var workTypeCodeParameter = workTypeCode != null ?
                new ObjectParameter("workTypeCode", workTypeCode) :
                new ObjectParameter("workTypeCode", typeof(string));
    
            var workTypeNameParameter = workTypeName != null ?
                new ObjectParameter("workTypeName", workTypeName) :
                new ObjectParameter("workTypeName", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("description", description) :
                new ObjectParameter("description", typeof(string));
    
            var workTypeCategoryIdParameter = workTypeCategoryId.HasValue ?
                new ObjectParameter("WorkTypeCategoryId", workTypeCategoryId) :
                new ObjectParameter("WorkTypeCategoryId", typeof(int));
    
            var isCapitalizableParameter = isCapitalizable.HasValue ?
                new ObjectParameter("isCapitalizable", isCapitalizable) :
                new ObjectParameter("isCapitalizable", typeof(int));
    
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("isActive", isActive) :
                new ObjectParameter("isActive", typeof(int));
    
            var updateUserIdParameter = updateUserId.HasValue ?
                new ObjectParameter("updateUserId", updateUserId) :
                new ObjectParameter("updateUserId", typeof(int));
    
            var workTypeIdParameter = workTypeId.HasValue ?
                new ObjectParameter("workTypeId", workTypeId) :
                new ObjectParameter("workTypeId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_WorkType_Update", workTypeCodeParameter, workTypeNameParameter, descriptionParameter, workTypeCategoryIdParameter, isCapitalizableParameter, isActiveParameter, updateUserIdParameter, workTypeIdParameter);
        }
    
        public virtual int usp_TimeEntry_Add(Nullable<int> employeeId, Nullable<int> workTypeId, Nullable<int> projectId, Nullable<int> projectItemId, string temCode, Nullable<System.DateTime> date, Nullable<decimal> workHour, string comments, string workItem, Nullable<int> createUserId, ObjectParameter timeEntryId)
        {
            var employeeIdParameter = employeeId.HasValue ?
                new ObjectParameter("employeeId", employeeId) :
                new ObjectParameter("employeeId", typeof(int));
    
            var workTypeIdParameter = workTypeId.HasValue ?
                new ObjectParameter("workTypeId", workTypeId) :
                new ObjectParameter("workTypeId", typeof(int));
    
            var projectIdParameter = projectId.HasValue ?
                new ObjectParameter("projectId", projectId) :
                new ObjectParameter("projectId", typeof(int));
    
            var projectItemIdParameter = projectItemId.HasValue ?
                new ObjectParameter("projectItemId", projectItemId) :
                new ObjectParameter("projectItemId", typeof(int));
    
            var temCodeParameter = temCode != null ?
                new ObjectParameter("temCode", temCode) :
                new ObjectParameter("temCode", typeof(string));
    
            var dateParameter = date.HasValue ?
                new ObjectParameter("date", date) :
                new ObjectParameter("date", typeof(System.DateTime));
    
            var workHourParameter = workHour.HasValue ?
                new ObjectParameter("workHour", workHour) :
                new ObjectParameter("workHour", typeof(decimal));
    
            var commentsParameter = comments != null ?
                new ObjectParameter("comments", comments) :
                new ObjectParameter("comments", typeof(string));
    
            var workItemParameter = workItem != null ?
                new ObjectParameter("workItem", workItem) :
                new ObjectParameter("workItem", typeof(string));
    
            var createUserIdParameter = createUserId.HasValue ?
                new ObjectParameter("createUserId", createUserId) :
                new ObjectParameter("createUserId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_TimeEntry_Add", employeeIdParameter, workTypeIdParameter, projectIdParameter, projectItemIdParameter, temCodeParameter, dateParameter, workHourParameter, commentsParameter, workItemParameter, createUserIdParameter, timeEntryId);
        }
    
        public virtual int usp_TimeEntry_Delete(string timeEntryId, Nullable<int> deleteUserId)
        {
            var timeEntryIdParameter = timeEntryId != null ?
                new ObjectParameter("timeEntryId", timeEntryId) :
                new ObjectParameter("timeEntryId", typeof(string));
    
            var deleteUserIdParameter = deleteUserId.HasValue ?
                new ObjectParameter("deleteUserId", deleteUserId) :
                new ObjectParameter("deleteUserId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_TimeEntry_Delete", timeEntryIdParameter, deleteUserIdParameter);
        }
    
        public virtual ObjectResult<usp_TimeEntry_Get_Result> usp_TimeEntry_Get(Nullable<int> timeEntryId, Nullable<int> employeeId, Nullable<System.DateTime> date)
        {
            var timeEntryIdParameter = timeEntryId.HasValue ?
                new ObjectParameter("timeEntryId", timeEntryId) :
                new ObjectParameter("timeEntryId", typeof(int));
    
            var employeeIdParameter = employeeId.HasValue ?
                new ObjectParameter("employeeId", employeeId) :
                new ObjectParameter("employeeId", typeof(int));
    
            var dateParameter = date.HasValue ?
                new ObjectParameter("date", date) :
                new ObjectParameter("date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_TimeEntry_Get_Result>("usp_TimeEntry_Get", timeEntryIdParameter, employeeIdParameter, dateParameter);
        }
    
        public virtual ObjectResult<usp_TimeEntry_GetWeeklyStatus_Result> usp_TimeEntry_GetWeeklyStatus(Nullable<int> employeeId, Nullable<int> monthsBack, Nullable<System.DateTime> productionDate, Nullable<System.DateTime> searchDate, Nullable<int> pageSize, Nullable<int> pageNumber)
        {
            var employeeIdParameter = employeeId.HasValue ?
                new ObjectParameter("employeeId", employeeId) :
                new ObjectParameter("employeeId", typeof(int));
    
            var monthsBackParameter = monthsBack.HasValue ?
                new ObjectParameter("monthsBack", monthsBack) :
                new ObjectParameter("monthsBack", typeof(int));
    
            var productionDateParameter = productionDate.HasValue ?
                new ObjectParameter("ProductionDate", productionDate) :
                new ObjectParameter("ProductionDate", typeof(System.DateTime));
    
            var searchDateParameter = searchDate.HasValue ?
                new ObjectParameter("searchDate", searchDate) :
                new ObjectParameter("searchDate", typeof(System.DateTime));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("pageSize", pageSize) :
                new ObjectParameter("pageSize", typeof(int));
    
            var pageNumberParameter = pageNumber.HasValue ?
                new ObjectParameter("pageNumber", pageNumber) :
                new ObjectParameter("pageNumber", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_TimeEntry_GetWeeklyStatus_Result>("usp_TimeEntry_GetWeeklyStatus", employeeIdParameter, monthsBackParameter, productionDateParameter, searchDateParameter, pageSizeParameter, pageNumberParameter);
        }
    
        public virtual ObjectResult<usp_TimeEntry_Search_Result> usp_TimeEntry_Search(Nullable<int> timeEntryId, Nullable<int> employeeId, Nullable<int> workTypeId, Nullable<int> projectId, Nullable<int> projectItemId, string searchBy, Nullable<System.DateTime> timeEntryDateFrom, Nullable<System.DateTime> timeEntryDateTo, Nullable<int> pageSize, Nullable<int> pageNumber, Nullable<bool> sortOrder, string sortColumn)
        {
            var timeEntryIdParameter = timeEntryId.HasValue ?
                new ObjectParameter("timeEntryId", timeEntryId) :
                new ObjectParameter("timeEntryId", typeof(int));
    
            var employeeIdParameter = employeeId.HasValue ?
                new ObjectParameter("employeeId", employeeId) :
                new ObjectParameter("employeeId", typeof(int));
    
            var workTypeIdParameter = workTypeId.HasValue ?
                new ObjectParameter("workTypeId", workTypeId) :
                new ObjectParameter("workTypeId", typeof(int));
    
            var projectIdParameter = projectId.HasValue ?
                new ObjectParameter("projectId", projectId) :
                new ObjectParameter("projectId", typeof(int));
    
            var projectItemIdParameter = projectItemId.HasValue ?
                new ObjectParameter("projectItemId", projectItemId) :
                new ObjectParameter("projectItemId", typeof(int));
    
            var searchByParameter = searchBy != null ?
                new ObjectParameter("searchBy", searchBy) :
                new ObjectParameter("searchBy", typeof(string));
    
            var timeEntryDateFromParameter = timeEntryDateFrom.HasValue ?
                new ObjectParameter("timeEntryDateFrom", timeEntryDateFrom) :
                new ObjectParameter("timeEntryDateFrom", typeof(System.DateTime));
    
            var timeEntryDateToParameter = timeEntryDateTo.HasValue ?
                new ObjectParameter("timeEntryDateTo", timeEntryDateTo) :
                new ObjectParameter("timeEntryDateTo", typeof(System.DateTime));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("pageSize", pageSize) :
                new ObjectParameter("pageSize", typeof(int));
    
            var pageNumberParameter = pageNumber.HasValue ?
                new ObjectParameter("pageNumber", pageNumber) :
                new ObjectParameter("pageNumber", typeof(int));
    
            var sortOrderParameter = sortOrder.HasValue ?
                new ObjectParameter("sortOrder", sortOrder) :
                new ObjectParameter("sortOrder", typeof(bool));
    
            var sortColumnParameter = sortColumn != null ?
                new ObjectParameter("sortColumn", sortColumn) :
                new ObjectParameter("sortColumn", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_TimeEntry_Search_Result>("usp_TimeEntry_Search", timeEntryIdParameter, employeeIdParameter, workTypeIdParameter, projectIdParameter, projectItemIdParameter, searchByParameter, timeEntryDateFromParameter, timeEntryDateToParameter, pageSizeParameter, pageNumberParameter, sortOrderParameter, sortColumnParameter);
        }
    
        public virtual int usp_TimeEntry_Update(Nullable<int> timeEntryId, Nullable<int> employeeId, Nullable<int> workTypeId, Nullable<int> projectId, Nullable<int> projectItemId, Nullable<System.DateTime> date, Nullable<decimal> workHour, string comments, string workItem, Nullable<int> updateUserId)
        {
            var timeEntryIdParameter = timeEntryId.HasValue ?
                new ObjectParameter("timeEntryId", timeEntryId) :
                new ObjectParameter("timeEntryId", typeof(int));
    
            var employeeIdParameter = employeeId.HasValue ?
                new ObjectParameter("employeeId", employeeId) :
                new ObjectParameter("employeeId", typeof(int));
    
            var workTypeIdParameter = workTypeId.HasValue ?
                new ObjectParameter("workTypeId", workTypeId) :
                new ObjectParameter("workTypeId", typeof(int));
    
            var projectIdParameter = projectId.HasValue ?
                new ObjectParameter("projectId", projectId) :
                new ObjectParameter("projectId", typeof(int));
    
            var projectItemIdParameter = projectItemId.HasValue ?
                new ObjectParameter("projectItemId", projectItemId) :
                new ObjectParameter("projectItemId", typeof(int));
    
            var dateParameter = date.HasValue ?
                new ObjectParameter("date", date) :
                new ObjectParameter("date", typeof(System.DateTime));
    
            var workHourParameter = workHour.HasValue ?
                new ObjectParameter("workHour", workHour) :
                new ObjectParameter("workHour", typeof(decimal));
    
            var commentsParameter = comments != null ?
                new ObjectParameter("comments", comments) :
                new ObjectParameter("comments", typeof(string));
    
            var workItemParameter = workItem != null ?
                new ObjectParameter("workItem", workItem) :
                new ObjectParameter("workItem", typeof(string));
    
            var updateUserIdParameter = updateUserId.HasValue ?
                new ObjectParameter("updateUserId", updateUserId) :
                new ObjectParameter("updateUserId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_TimeEntry_Update", timeEntryIdParameter, employeeIdParameter, workTypeIdParameter, projectIdParameter, projectItemIdParameter, dateParameter, workHourParameter, commentsParameter, workItemParameter, updateUserIdParameter);
        }
    
        public virtual int usp_Project_Add(string projectName, string projectDescription, Nullable<int> projectTypeId, Nullable<int> createUserId, ObjectParameter projectId)
        {
            var projectNameParameter = projectName != null ?
                new ObjectParameter("projectName", projectName) :
                new ObjectParameter("projectName", typeof(string));
    
            var projectDescriptionParameter = projectDescription != null ?
                new ObjectParameter("projectDescription", projectDescription) :
                new ObjectParameter("projectDescription", typeof(string));
    
            var projectTypeIdParameter = projectTypeId.HasValue ?
                new ObjectParameter("projectTypeId", projectTypeId) :
                new ObjectParameter("projectTypeId", typeof(int));
    
            var createUserIdParameter = createUserId.HasValue ?
                new ObjectParameter("createUserId", createUserId) :
                new ObjectParameter("createUserId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_Project_Add", projectNameParameter, projectDescriptionParameter, projectTypeIdParameter, createUserIdParameter, projectId);
        }
    
        public virtual ObjectResult<usp_Project_Get_Result> usp_Project_Get(Nullable<int> isActive)
        {
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("isActive", isActive) :
                new ObjectParameter("isActive", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_Project_Get_Result>("usp_Project_Get", isActiveParameter);
        }
    
        public virtual ObjectResult<usp_Project_Search_Result> usp_Project_Search(Nullable<int> projectId, string searchBy, Nullable<int> pageSize, Nullable<int> pageNumber, Nullable<bool> sortOrder, string sortColumn)
        {
            var projectIdParameter = projectId.HasValue ?
                new ObjectParameter("projectId", projectId) :
                new ObjectParameter("projectId", typeof(int));
    
            var searchByParameter = searchBy != null ?
                new ObjectParameter("searchBy", searchBy) :
                new ObjectParameter("searchBy", typeof(string));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("pageSize", pageSize) :
                new ObjectParameter("pageSize", typeof(int));
    
            var pageNumberParameter = pageNumber.HasValue ?
                new ObjectParameter("pageNumber", pageNumber) :
                new ObjectParameter("pageNumber", typeof(int));
    
            var sortOrderParameter = sortOrder.HasValue ?
                new ObjectParameter("sortOrder", sortOrder) :
                new ObjectParameter("sortOrder", typeof(bool));
    
            var sortColumnParameter = sortColumn != null ?
                new ObjectParameter("sortColumn", sortColumn) :
                new ObjectParameter("sortColumn", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_Project_Search_Result>("usp_Project_Search", projectIdParameter, searchByParameter, pageSizeParameter, pageNumberParameter, sortOrderParameter, sortColumnParameter);
        }
    
        public virtual int usp_Project_Update(string projectName, string projectDescription, Nullable<int> projectTypeId, Nullable<int> isActive, Nullable<int> updateUserId, Nullable<int> projectId)
        {
            var projectNameParameter = projectName != null ?
                new ObjectParameter("projectName", projectName) :
                new ObjectParameter("projectName", typeof(string));
    
            var projectDescriptionParameter = projectDescription != null ?
                new ObjectParameter("projectDescription", projectDescription) :
                new ObjectParameter("projectDescription", typeof(string));
    
            var projectTypeIdParameter = projectTypeId.HasValue ?
                new ObjectParameter("projectTypeId", projectTypeId) :
                new ObjectParameter("projectTypeId", typeof(int));
    
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("isActive", isActive) :
                new ObjectParameter("isActive", typeof(int));
    
            var updateUserIdParameter = updateUserId.HasValue ?
                new ObjectParameter("updateUserId", updateUserId) :
                new ObjectParameter("updateUserId", typeof(int));
    
            var projectIdParameter = projectId.HasValue ?
                new ObjectParameter("projectId", projectId) :
                new ObjectParameter("projectId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_Project_Update", projectNameParameter, projectDescriptionParameter, projectTypeIdParameter, isActiveParameter, updateUserIdParameter, projectIdParameter);
        }
    
        public virtual int usp_ProjectItem_Add(string projectItemName, string projectItemDescription, Nullable<int> projectId, Nullable<int> projectItemStatusId, Nullable<decimal> budget, Nullable<decimal> benefit, Nullable<decimal> devLOE, Nullable<decimal> qaLOE, Nullable<decimal> baLOE, Nullable<int> createUserId, ObjectParameter projectItemId)
        {
            var projectItemNameParameter = projectItemName != null ?
                new ObjectParameter("projectItemName", projectItemName) :
                new ObjectParameter("projectItemName", typeof(string));
    
            var projectItemDescriptionParameter = projectItemDescription != null ?
                new ObjectParameter("projectItemDescription", projectItemDescription) :
                new ObjectParameter("projectItemDescription", typeof(string));
    
            var projectIdParameter = projectId.HasValue ?
                new ObjectParameter("projectId", projectId) :
                new ObjectParameter("projectId", typeof(int));
    
            var projectItemStatusIdParameter = projectItemStatusId.HasValue ?
                new ObjectParameter("projectItemStatusId", projectItemStatusId) :
                new ObjectParameter("projectItemStatusId", typeof(int));
    
            var budgetParameter = budget.HasValue ?
                new ObjectParameter("budget", budget) :
                new ObjectParameter("budget", typeof(decimal));
    
            var benefitParameter = benefit.HasValue ?
                new ObjectParameter("benefit", benefit) :
                new ObjectParameter("benefit", typeof(decimal));
    
            var devLOEParameter = devLOE.HasValue ?
                new ObjectParameter("devLOE", devLOE) :
                new ObjectParameter("devLOE", typeof(decimal));
    
            var qaLOEParameter = qaLOE.HasValue ?
                new ObjectParameter("qaLOE", qaLOE) :
                new ObjectParameter("qaLOE", typeof(decimal));
    
            var baLOEParameter = baLOE.HasValue ?
                new ObjectParameter("baLOE", baLOE) :
                new ObjectParameter("baLOE", typeof(decimal));
    
            var createUserIdParameter = createUserId.HasValue ?
                new ObjectParameter("createUserId", createUserId) :
                new ObjectParameter("createUserId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_ProjectItem_Add", projectItemNameParameter, projectItemDescriptionParameter, projectIdParameter, projectItemStatusIdParameter, budgetParameter, benefitParameter, devLOEParameter, qaLOEParameter, baLOEParameter, createUserIdParameter, projectItemId);
        }
    
        public virtual ObjectResult<usp_ProjectItem_Get_Result> usp_ProjectItem_Get(Nullable<int> isActive, Nullable<int> projectId)
        {
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("isActive", isActive) :
                new ObjectParameter("isActive", typeof(int));
    
            var projectIdParameter = projectId.HasValue ?
                new ObjectParameter("projectId", projectId) :
                new ObjectParameter("projectId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ProjectItem_Get_Result>("usp_ProjectItem_Get", isActiveParameter, projectIdParameter);
        }
    
        public virtual ObjectResult<usp_ProjectItem_Search_Result> usp_ProjectItem_Search(Nullable<int> projectItemId, string searchBy, Nullable<int> pageSize, Nullable<int> pageNumber, Nullable<bool> sortOrder, string sortColumn)
        {
            var projectItemIdParameter = projectItemId.HasValue ?
                new ObjectParameter("projectItemId", projectItemId) :
                new ObjectParameter("projectItemId", typeof(int));
    
            var searchByParameter = searchBy != null ?
                new ObjectParameter("searchBy", searchBy) :
                new ObjectParameter("searchBy", typeof(string));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("pageSize", pageSize) :
                new ObjectParameter("pageSize", typeof(int));
    
            var pageNumberParameter = pageNumber.HasValue ?
                new ObjectParameter("pageNumber", pageNumber) :
                new ObjectParameter("pageNumber", typeof(int));
    
            var sortOrderParameter = sortOrder.HasValue ?
                new ObjectParameter("sortOrder", sortOrder) :
                new ObjectParameter("sortOrder", typeof(bool));
    
            var sortColumnParameter = sortColumn != null ?
                new ObjectParameter("sortColumn", sortColumn) :
                new ObjectParameter("sortColumn", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ProjectItem_Search_Result>("usp_ProjectItem_Search", projectItemIdParameter, searchByParameter, pageSizeParameter, pageNumberParameter, sortOrderParameter, sortColumnParameter);
        }
    
        public virtual int usp_ProjectItem_Update(string projectItemName, string projectItemDescription, Nullable<int> projectId, Nullable<int> projectItemStatusId, Nullable<decimal> budget, Nullable<decimal> benefit, Nullable<decimal> devLOE, Nullable<decimal> qaLOE, Nullable<decimal> baLOE, Nullable<int> isActive, Nullable<int> updateUserId, Nullable<int> projectItemId)
        {
            var projectItemNameParameter = projectItemName != null ?
                new ObjectParameter("projectItemName", projectItemName) :
                new ObjectParameter("projectItemName", typeof(string));
    
            var projectItemDescriptionParameter = projectItemDescription != null ?
                new ObjectParameter("projectItemDescription", projectItemDescription) :
                new ObjectParameter("projectItemDescription", typeof(string));
    
            var projectIdParameter = projectId.HasValue ?
                new ObjectParameter("projectId", projectId) :
                new ObjectParameter("projectId", typeof(int));
    
            var projectItemStatusIdParameter = projectItemStatusId.HasValue ?
                new ObjectParameter("projectItemStatusId", projectItemStatusId) :
                new ObjectParameter("projectItemStatusId", typeof(int));
    
            var budgetParameter = budget.HasValue ?
                new ObjectParameter("budget", budget) :
                new ObjectParameter("budget", typeof(decimal));
    
            var benefitParameter = benefit.HasValue ?
                new ObjectParameter("benefit", benefit) :
                new ObjectParameter("benefit", typeof(decimal));
    
            var devLOEParameter = devLOE.HasValue ?
                new ObjectParameter("devLOE", devLOE) :
                new ObjectParameter("devLOE", typeof(decimal));
    
            var qaLOEParameter = qaLOE.HasValue ?
                new ObjectParameter("qaLOE", qaLOE) :
                new ObjectParameter("qaLOE", typeof(decimal));
    
            var baLOEParameter = baLOE.HasValue ?
                new ObjectParameter("baLOE", baLOE) :
                new ObjectParameter("baLOE", typeof(decimal));
    
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("isActive", isActive) :
                new ObjectParameter("isActive", typeof(int));
    
            var updateUserIdParameter = updateUserId.HasValue ?
                new ObjectParameter("updateUserId", updateUserId) :
                new ObjectParameter("updateUserId", typeof(int));
    
            var projectItemIdParameter = projectItemId.HasValue ?
                new ObjectParameter("projectItemId", projectItemId) :
                new ObjectParameter("projectItemId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_ProjectItem_Update", projectItemNameParameter, projectItemDescriptionParameter, projectIdParameter, projectItemStatusIdParameter, budgetParameter, benefitParameter, devLOEParameter, qaLOEParameter, baLOEParameter, isActiveParameter, updateUserIdParameter, projectItemIdParameter);
        }
    
        public virtual ObjectResult<usp_ReportRegistry_Detail_Result> usp_ReportRegistry_Detail(Nullable<int> userTypeId)
        {
            var userTypeIdParameter = userTypeId.HasValue ?
                new ObjectParameter("userTypeId", userTypeId) :
                new ObjectParameter("userTypeId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ReportRegistry_Detail_Result>("usp_ReportRegistry_Detail", userTypeIdParameter);
        }
    
        public virtual ObjectResult<usp_Employee_Authentication_Result> usp_Employee_Authentication(string logonName, string logonPassword)
        {
            var logonNameParameter = logonName != null ?
                new ObjectParameter("logonName", logonName) :
                new ObjectParameter("logonName", typeof(string));
    
            var logonPasswordParameter = logonPassword != null ?
                new ObjectParameter("logonPassword", logonPassword) :
                new ObjectParameter("logonPassword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_Employee_Authentication_Result>("usp_Employee_Authentication", logonNameParameter, logonPasswordParameter);
        }
    
        public virtual ObjectResult<usp_TimeEntry_GetDistinctRecords_Result> usp_TimeEntry_GetDistinctRecords(Nullable<int> employeeId, Nullable<System.DateTime> date)
        {
            var employeeIdParameter = employeeId.HasValue ?
                new ObjectParameter("employeeId", employeeId) :
                new ObjectParameter("employeeId", typeof(int));
    
            var dateParameter = date.HasValue ?
                new ObjectParameter("date", date) :
                new ObjectParameter("date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_TimeEntry_GetDistinctRecords_Result>("usp_TimeEntry_GetDistinctRecords", employeeIdParameter, dateParameter);
        }
    
        public virtual ObjectResult<usp_TimeEntry_GetProjectView_Result> usp_TimeEntry_GetProjectView(Nullable<int> projectId, Nullable<int> monthsBack, Nullable<System.DateTime> productionDate, Nullable<System.DateTime> searchDate, Nullable<int> pageSize, Nullable<int> pageNumber)
        {
            var projectIdParameter = projectId.HasValue ?
                new ObjectParameter("projectId", projectId) :
                new ObjectParameter("projectId", typeof(int));
    
            var monthsBackParameter = monthsBack.HasValue ?
                new ObjectParameter("monthsBack", monthsBack) :
                new ObjectParameter("monthsBack", typeof(int));
    
            var productionDateParameter = productionDate.HasValue ?
                new ObjectParameter("ProductionDate", productionDate) :
                new ObjectParameter("ProductionDate", typeof(System.DateTime));
    
            var searchDateParameter = searchDate.HasValue ?
                new ObjectParameter("searchDate", searchDate) :
                new ObjectParameter("searchDate", typeof(System.DateTime));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("pageSize", pageSize) :
                new ObjectParameter("pageSize", typeof(int));
    
            var pageNumberParameter = pageNumber.HasValue ?
                new ObjectParameter("pageNumber", pageNumber) :
                new ObjectParameter("pageNumber", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_TimeEntry_GetProjectView_Result>("usp_TimeEntry_GetProjectView", projectIdParameter, monthsBackParameter, productionDateParameter, searchDateParameter, pageSizeParameter, pageNumberParameter);
        }
    
        public virtual ObjectResult<usp_TimeEntry_GetProjectViewForExport_Result> usp_TimeEntry_GetProjectViewForExport(Nullable<int> projectId, Nullable<int> monthsBack, Nullable<System.DateTime> productionDate, Nullable<System.DateTime> searchDate, Nullable<int> pageSize, Nullable<int> pageNumber)
        {
            var projectIdParameter = projectId.HasValue ?
                new ObjectParameter("projectId", projectId) :
                new ObjectParameter("projectId", typeof(int));
    
            var monthsBackParameter = monthsBack.HasValue ?
                new ObjectParameter("monthsBack", monthsBack) :
                new ObjectParameter("monthsBack", typeof(int));
    
            var productionDateParameter = productionDate.HasValue ?
                new ObjectParameter("ProductionDate", productionDate) :
                new ObjectParameter("ProductionDate", typeof(System.DateTime));
    
            var searchDateParameter = searchDate.HasValue ?
                new ObjectParameter("searchDate", searchDate) :
                new ObjectParameter("searchDate", typeof(System.DateTime));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("pageSize", pageSize) :
                new ObjectParameter("pageSize", typeof(int));
    
            var pageNumberParameter = pageNumber.HasValue ?
                new ObjectParameter("pageNumber", pageNumber) :
                new ObjectParameter("pageNumber", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_TimeEntry_GetProjectViewForExport_Result>("usp_TimeEntry_GetProjectViewForExport", projectIdParameter, monthsBackParameter, productionDateParameter, searchDateParameter, pageSizeParameter, pageNumberParameter);
        }
    
        public virtual ObjectResult<usp_Employee_Search_Result> usp_Employee_Search(Nullable<int> employeeId, Nullable<int> managerId, string searchBy, Nullable<int> pageSize, Nullable<int> pageNumber, Nullable<bool> sortOrder, string sortColumn)
        {
            var employeeIdParameter = employeeId.HasValue ?
                new ObjectParameter("employeeId", employeeId) :
                new ObjectParameter("employeeId", typeof(int));
    
            var managerIdParameter = managerId.HasValue ?
                new ObjectParameter("managerId", managerId) :
                new ObjectParameter("managerId", typeof(int));
    
            var searchByParameter = searchBy != null ?
                new ObjectParameter("searchBy", searchBy) :
                new ObjectParameter("searchBy", typeof(string));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("pageSize", pageSize) :
                new ObjectParameter("pageSize", typeof(int));
    
            var pageNumberParameter = pageNumber.HasValue ?
                new ObjectParameter("pageNumber", pageNumber) :
                new ObjectParameter("pageNumber", typeof(int));
    
            var sortOrderParameter = sortOrder.HasValue ?
                new ObjectParameter("sortOrder", sortOrder) :
                new ObjectParameter("sortOrder", typeof(bool));
    
            var sortColumnParameter = sortColumn != null ?
                new ObjectParameter("sortColumn", sortColumn) :
                new ObjectParameter("sortColumn", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_Employee_Search_Result>("usp_Employee_Search", employeeIdParameter, managerIdParameter, searchByParameter, pageSizeParameter, pageNumberParameter, sortOrderParameter, sortColumnParameter);
        }
    
        public virtual int usp_Employee_Update(Nullable<int> employeeId, string firstName, string lastName, Nullable<System.DateTime> dOJ, string designation, Nullable<int> timeZoneId, Nullable<int> teamId, Nullable<int> managerId, Nullable<int> locationId, Nullable<int> employmentTypeId, string companyName, Nullable<int> userTypeId, Nullable<int> isTimeEntryEnable, Nullable<int> isActive, Nullable<int> updateUserId, Nullable<System.DateTime> dOT)
        {
            var employeeIdParameter = employeeId.HasValue ?
                new ObjectParameter("employeeId", employeeId) :
                new ObjectParameter("employeeId", typeof(int));
    
            var firstNameParameter = firstName != null ?
                new ObjectParameter("firstName", firstName) :
                new ObjectParameter("firstName", typeof(string));
    
            var lastNameParameter = lastName != null ?
                new ObjectParameter("lastName", lastName) :
                new ObjectParameter("lastName", typeof(string));
    
            var dOJParameter = dOJ.HasValue ?
                new ObjectParameter("dOJ", dOJ) :
                new ObjectParameter("dOJ", typeof(System.DateTime));
    
            var designationParameter = designation != null ?
                new ObjectParameter("designation", designation) :
                new ObjectParameter("designation", typeof(string));
    
            var timeZoneIdParameter = timeZoneId.HasValue ?
                new ObjectParameter("timeZoneId", timeZoneId) :
                new ObjectParameter("timeZoneId", typeof(int));
    
            var teamIdParameter = teamId.HasValue ?
                new ObjectParameter("teamId", teamId) :
                new ObjectParameter("teamId", typeof(int));
    
            var managerIdParameter = managerId.HasValue ?
                new ObjectParameter("managerId", managerId) :
                new ObjectParameter("managerId", typeof(int));
    
            var locationIdParameter = locationId.HasValue ?
                new ObjectParameter("locationId", locationId) :
                new ObjectParameter("locationId", typeof(int));
    
            var employmentTypeIdParameter = employmentTypeId.HasValue ?
                new ObjectParameter("employmentTypeId", employmentTypeId) :
                new ObjectParameter("employmentTypeId", typeof(int));
    
            var companyNameParameter = companyName != null ?
                new ObjectParameter("companyName", companyName) :
                new ObjectParameter("companyName", typeof(string));
    
            var userTypeIdParameter = userTypeId.HasValue ?
                new ObjectParameter("userTypeId", userTypeId) :
                new ObjectParameter("userTypeId", typeof(int));
    
            var isTimeEntryEnableParameter = isTimeEntryEnable.HasValue ?
                new ObjectParameter("isTimeEntryEnable", isTimeEntryEnable) :
                new ObjectParameter("isTimeEntryEnable", typeof(int));
    
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("isActive", isActive) :
                new ObjectParameter("isActive", typeof(int));
    
            var updateUserIdParameter = updateUserId.HasValue ?
                new ObjectParameter("updateUserId", updateUserId) :
                new ObjectParameter("updateUserId", typeof(int));
    
            var dOTParameter = dOT.HasValue ?
                new ObjectParameter("dOT", dOT) :
                new ObjectParameter("dOT", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_Employee_Update", employeeIdParameter, firstNameParameter, lastNameParameter, dOJParameter, designationParameter, timeZoneIdParameter, teamIdParameter, managerIdParameter, locationIdParameter, employmentTypeIdParameter, companyNameParameter, userTypeIdParameter, isTimeEntryEnableParameter, isActiveParameter, updateUserIdParameter, dOTParameter);
        }
    
        public virtual int usp_Employee_Add(string logonName, string firstName, string lastName, string emailAddress, Nullable<System.DateTime> dOJ, string designation, Nullable<int> timeZoneId, Nullable<int> teamId, Nullable<int> managerId, Nullable<int> locationId, Nullable<int> employmentTypeId, string companyName, Nullable<int> userTypeId, Nullable<int> isTimeEntryEnable, Nullable<int> createUserId, ObjectParameter employeeId, Nullable<System.DateTime> dOT)
        {
            var logonNameParameter = logonName != null ?
                new ObjectParameter("logonName", logonName) :
                new ObjectParameter("logonName", typeof(string));
    
            var firstNameParameter = firstName != null ?
                new ObjectParameter("firstName", firstName) :
                new ObjectParameter("firstName", typeof(string));
    
            var lastNameParameter = lastName != null ?
                new ObjectParameter("lastName", lastName) :
                new ObjectParameter("lastName", typeof(string));
    
            var emailAddressParameter = emailAddress != null ?
                new ObjectParameter("emailAddress", emailAddress) :
                new ObjectParameter("emailAddress", typeof(string));
    
            var dOJParameter = dOJ.HasValue ?
                new ObjectParameter("dOJ", dOJ) :
                new ObjectParameter("dOJ", typeof(System.DateTime));
    
            var designationParameter = designation != null ?
                new ObjectParameter("designation", designation) :
                new ObjectParameter("designation", typeof(string));
    
            var timeZoneIdParameter = timeZoneId.HasValue ?
                new ObjectParameter("timeZoneId", timeZoneId) :
                new ObjectParameter("timeZoneId", typeof(int));
    
            var teamIdParameter = teamId.HasValue ?
                new ObjectParameter("teamId", teamId) :
                new ObjectParameter("teamId", typeof(int));
    
            var managerIdParameter = managerId.HasValue ?
                new ObjectParameter("managerId", managerId) :
                new ObjectParameter("managerId", typeof(int));
    
            var locationIdParameter = locationId.HasValue ?
                new ObjectParameter("locationId", locationId) :
                new ObjectParameter("locationId", typeof(int));
    
            var employmentTypeIdParameter = employmentTypeId.HasValue ?
                new ObjectParameter("employmentTypeId", employmentTypeId) :
                new ObjectParameter("employmentTypeId", typeof(int));
    
            var companyNameParameter = companyName != null ?
                new ObjectParameter("companyName", companyName) :
                new ObjectParameter("companyName", typeof(string));
    
            var userTypeIdParameter = userTypeId.HasValue ?
                new ObjectParameter("userTypeId", userTypeId) :
                new ObjectParameter("userTypeId", typeof(int));
    
            var isTimeEntryEnableParameter = isTimeEntryEnable.HasValue ?
                new ObjectParameter("isTimeEntryEnable", isTimeEntryEnable) :
                new ObjectParameter("isTimeEntryEnable", typeof(int));
    
            var createUserIdParameter = createUserId.HasValue ?
                new ObjectParameter("createUserId", createUserId) :
                new ObjectParameter("createUserId", typeof(int));
    
            var dOTParameter = dOT.HasValue ?
                new ObjectParameter("dOT", dOT) :
                new ObjectParameter("dOT", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_Employee_Add", logonNameParameter, firstNameParameter, lastNameParameter, emailAddressParameter, dOJParameter, designationParameter, timeZoneIdParameter, teamIdParameter, managerIdParameter, locationIdParameter, employmentTypeIdParameter, companyNameParameter, userTypeIdParameter, isTimeEntryEnableParameter, createUserIdParameter, employeeId, dOTParameter);
        }
    }
}
